platform :ios,'11.0'

target 'ParentsWeekend' do
	pod 'AMTagListView','~> 1.5.0'
	pod 'DAPagesContainer','~> 1.0.1'
	pod 'AFNetworking','~> 3.1.0'
	pod 'SDWebImage','~> 4.0.0'
	pod 'JSONKit','~> 1.5pre'
	pod 'Mantle','~> 2.1.0'
	pod 'Masonry','~> 1.0.2'
	pod 'NullSafe','~> 1.2.2'
	pod 'SVProgressHUD','~> 2.1.2'
end
